---
kind: pipeline
type: docker
name: amd64
platform:
  os: linux
  arсh: amd64
steps:
  - name: info
    image: alpine
    commands:
      - uname -a
---
kind: pipeline
type: docker
name: arm64
platform:
  os: linux
  arсh: arm64
  variant: armv8
steps:
  - name: greeting
    image: alpine
    commands:
      - uname -a
